apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: ruthvikc27/service-2

---

apiVersion: v1
kind: Service
metadata:
  name: service-2-srv
spec:
  type: ClusterIP
  selector:
    app: service-2
  ports:
    - name: service-2
      protocol: TCP
      port: 5000
      targetPort: 5000