apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: ruthvikc27/service-2
          env: 
            - name: MONGO_URI
              value: mongodb://service-2-mongo-srv:27017/service-2
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY
         

---

apiVersion: v1
kind: Service
metadata:
  name: service-2-srv
spec:
  type: ClusterIP
  selector:
    app: service-2
  ports:
    - name: service-2
      protocol: TCP
      port: 5000
      targetPort: 5000